# Generated by Django 3.2 on 2021-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_task_name', models.CharField(default='default_name', max_length=200)),
                ('task_id', models.CharField(max_length=200)),
            ],
        ),
    ]
