# Generated by Django 3.2 on 2021-05-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celery_monitor', '0003_auto_20210516_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskwithCustomTaskName',
            fields=[
                ('taskstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='celery_monitor.taskstate')),
                ('custom_taskname', models.CharField(db_index=True, max_length=200, null=True, verbose_name='custom task name')),
            ],
            bases=('celery_monitor.taskstate',),
        ),
    ]
