# Generated by Django 3.2 on 2021-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskname',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='taskwithcustomtaskname',
            name='custom_taskname',
        ),
        migrations.AddField(
            model_name='taskname',
            name='custom_task_name',
            field=models.CharField(default='default_name', max_length=200),
        ),
        migrations.AddField(
            model_name='taskwithcustomtaskname',
            name='custom_task_name',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='custom task name'),
        ),
    ]
